### PR TITLE
tidy up, add gulp, little things

### PR DESCRIPTION
**Pull request by benhinchley**
Starting this PR early, but I plan on refactoring the CSS and some of the UI elements to make them more inline with their counterparts on the Peach :peach:  mobile app.

### CODE REVIEW

**Comment by ummjackson** [comment]
😻Really appreciate the help, mimicking the UI has been tedious so far!!

**Comment by benhinchley** [comment]
@ummjackson all good :+1:

**Comment by benhinchley** [comment]
@ummjackson just thinking about it this is gonna be a big pr, do you want me to break it up into smaller chunks?

**Comment by ummjackson** [comment]
Might make sense to break it up so the improvement is incremental. Thoughts?

**Comment by ummjackson** [comment]
@benhinchley Let me know if the progress so far is ready to go and I can test / merge.

**Comment by benhinchley** [comment]
yeah it is probably going to be easier to manage with incremental up dates.

@ummjackson let me see if I have anything left in this initial kinda tidy up to do, but I think this is ready/could merge

**Comment by ummjackson** [comment]
Looking good I think... are there any instructions to change in the README for running?

**Comment by benhinchley** [comment]
Yeah this should all be good, and nope it should all still work the same way that the README says

**Comment by ummjackson** [comment]
Merge time!

**Comment by ummjackson** [comment]
@benhinchley - some sort of regression here, the loader is now not working on load

**Comment by ummjackson** [comment]
Reverted.

**Pull request merged**
