### PR TITLE
add a loader

### PR DESCRIPTION
**Pull request by benhinchley**
added a loader to help with the transition between views, as it currently can be difficult to tell if your button press is actually doing something

Signed-off-by: Benjamin Hinchley <benjaminhinchley@gmail.com>

### CODE REVIEW

**Comment by ummjackson** [comment]
I really dig this (was trying to do something similar with sliding views via Velocity.js) but worry about blocking the entire existing view then flash switching. Do you mind experimenting with perhaps a semi-transparent overlay so you still get a peek of the view you're leaving in the background?

Also want to add button press animations at some point, to make it feel more interactive and less like a web page.

**Comment by benhinchley** [comment]
yeah sure will play around with that, try and screen shot some different variations and put them in here

**Comment by benhinchley** [comment]
peach_desktop_and_peach-desktop_ _working_copy__add-loader_ _1_changed_files_

loader now looks like so ^

**Comment by ummjackson** [comment]
Ok, this is spiffy. Merging. :+1:  :100:

**Comment by benhinchley** [comment]
woop @ummjackson :tada:

**Pull request merged**
